adding nodemailer structure and configuring arquitecture
dlab-team/c6-backend pull request #15
Opened 2023-01-05 02:24 UTC by Strike2-ux

I did have problems with the structure of the Architecture, but what I add to the code is not too far from reality, we need nodemailer and declare the api/auth/recovery & install the utils, please check it if am i wrong (probably), keep foward to the development.

2023-01-05 14:58 UTC, ViloriaUrdaneta commented
> I did have problems with the structure of the Architecture, but what I add to the code is not too far from reality, we need nodemailer and declare the api/auth/recovery & install the utils, please check it if am i wrong (probably), keep foward to the development.

I'm a bit confused by the change of architecture because I was already working on the basis of the previous one.
I think token.utils.js is the same as jwt.js.

2023-01-06 17:52 UTC, AlfredoVillegas requested changes
creo que hay archivos que no iban en este commit, y los añadiste por error. pudes revisarlo nuevamente?

2023-01-06 17:52 UTC, AlfredoVillegas commented on server.js
> +import express from 'express';
cual seria la intencion de este archivo ?. 
ya estamos estructurando la app y levantandola en el index.js del nivel superior en la estructura de carpetas

2023-01-06 17:52 UTC, AlfredoVillegas commented on server.js
> +
creo que son rutas que no manejamos

2023-01-06 17:52 UTC, AlfredoVillegas commented on src/models/index.js
> +'use strict'
ya hay una configuracion que establece squilize, esta dento de stc/database/sequelize.js

2023-01-10 15:10 UTC, closed without merging